require('dotenv').config();

module.exports = {
    GEMINI_API_KEY: process.env.GEMINI_API_KEY,
    BUSINESS_MORNING_START: process.env.BUSINESS_MORNING_START || '08:30',
    BUSINESS_MORNING_END: process.env.BUSINESS_MORNING_END || '12:30',
    BUSINESS_AFTERNOON_START: process.env.BUSINESS_AFTERNOON_START || '14:00',
    BUSINESS_AFTERNOON_END: process.env.BUSINESS_AFTERNOON_END || '18:00',
};
